import type { Metadata } from "next";
import { Outfit, Fustat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const fustat = Fustat({
  variable: "--font-fustat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tasks",
  description: "Generated by create next app",
};

const nohemi = localFont({
  src: [
    {
      path: "../public/fonts/Nohemi-Bold-BF6438cc577b524.woff",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-nohemi",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nohemi.variable} ${outfit.variable} ${fustat.variable} antialiased bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
